---
- name: Install Apache and configure a basic web server
  hosts: webservers
  become: true
  tasks:
    - name: Install Apache web server
      apt:
        name: apache2
        state: present
      tags:
        - install
    - name: Ensure Apache service is running
      service:
        name: apache2
        state: started
      tags:
        - configure
    - name: Enable Apache service at boot
      service:
        name: apache2
        enabled: yes
      tags:
        - configure
    - name: Copy index.html to web server
      copy:
        src: index.html
        dest: /var/www/html/index.html
      tags:
        - content
        